apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cogniforge
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/limit-rps: "100"
spec:
  tls:
    - hosts:
        - cogniforge.com
        - www.cogniforge.com
      secretName: cogniforge-prod-tls
  rules:
    - host: cogniforge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cogniforge
                port:
                  name: http
    - host: www.cogniforge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cogniforge
                port:
                  name: http
