apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cogniforge
spec:
  tls:
    - hosts:
        - dev.cogniforge.com
      secretName: cogniforge-dev-tls
  rules:
    - host: dev.cogniforge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cogniforge
                port:
                  name: http
