apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

namePrefix: staging-

commonLabels:
  environment: staging
  managed-by: kustomize

bases:
  - ../../base

replicas:
  - name: cogniforge
    count: 2

images:
  - name: CONTAINER_IMAGE_PLACEHOLDER
    newName: registry.gitlab.com/cogniforge/cogniforge
    newTag: staging

configMapGenerator:
  - name: cogniforge-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=INFO

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

resources:
  - namespace.yaml
