apiVersion: v1
kind: ServiceAccount
metadata:
  name: cogniforge
  labels:
    app: cogniforge
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cogniforge
  labels:
    app: cogniforge
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cogniforge
  labels:
    app: cogniforge
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cogniforge
subjects:
  - kind: ServiceAccount
    name: cogniforge
